export const BITMASK_PERMISSION_MODULE_OPTIONS =
  'BITMASK_PERMISSION_MODULE_OPTIONS';
export const BITMASK_USER_SERVICE = 'BITMASK_USER_SERVICE';
export const BITMASK_PERMISSIONS_TOKEN = 'BITMASK_PERMISSIONS_TOKEN';
